In [2]:
#1. Write a NumPy program to test whether none of the elements of a given array is zero & 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.
import numpy as np
no_zero=False
arr=[0,1,2,3,4,5,6,7,8,9]
np.array(arr)
if np.all(arr):
  no_zero=True
if no_zero:
  print("Array has no zero elements")
else:
  print("Array has zero elements")

Array has zero elements


In [3]:
#3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given
arr1=[1,2,3,4,5]
arr2=[1,2,3,4,6]
np.array(arr1)
np.array(arr2)
np.equal(arr1,arr2)

array([ True,  True,  True,  True, False])

In [4]:
# 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
a1=np.zeros(10)
a2=np.ones(10)
a3=np.full(10,5)
a4=np.hstack((a1,a2,a3))
a4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
#5. Write a NumPy program to create an array of the integers from 30 to70
a1=np.arange(30,71)
a1

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [6]:
#6. Write a NumPy program to create a 3x3 identity matrix
a1=np.identity(3)
a1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#7. Write a NumPy program to generate a random number between 0 and 1
x=np.random.rand()
x

0.8333629480740121

In [8]:
#8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution
arr=np.random.randn(15)
arr

array([ 1.11796247,  1.75579832, -0.80665755,  1.30127778,  0.11165855,
        0.44343868, -1.46462642,  0.70443347,  0.69497237,  1.01333434,
       -0.67547056, -0.52901623,  1.66570555, -0.31865064, -0.81357871])

In [9]:
# 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
arr=np.linspace(15,55)
arr[1:-1]

array([15.81632653, 16.63265306, 17.44897959, 18.26530612, 19.08163265,
       19.89795918, 20.71428571, 21.53061224, 22.34693878, 23.16326531,
       23.97959184, 24.79591837, 25.6122449 , 26.42857143, 27.24489796,
       28.06122449, 28.87755102, 29.69387755, 30.51020408, 31.32653061,
       32.14285714, 32.95918367, 33.7755102 , 34.59183673, 35.40816327,
       36.2244898 , 37.04081633, 37.85714286, 38.67346939, 39.48979592,
       40.30612245, 41.12244898, 41.93877551, 42.75510204, 43.57142857,
       44.3877551 , 45.20408163, 46.02040816, 46.83673469, 47.65306122,
       48.46938776, 49.28571429, 50.10204082, 50.91836735, 51.73469388,
       52.55102041, 53.36734694, 54.18367347])

In [10]:
# 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10
a=np.random.random_integers(0,11,5)
print(a)
b=np.random.randint(0,11,5)
b

[ 4  6  2 11  8]


<ipython-input-10-477274d6ab68>:2: DeprecationWarning: This function is deprecated. Please call randint(0, 11 + 1) instead
  a=np.random.random_integers(0,11,5)


array([5, 0, 4, 5, 2])

In [11]:
# 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
m=np.zeros((10,10))
m[0],m[-1],m[:,0],m[:,-1]=1,1,1,1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
# 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
a=np.zeros((5,5))
for i in range(0,5):
  a[i,i]=i+1
a

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [43]:
# 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
a=np.ones((4,4))
for i in range(0,4):
  a[i,i]=0
a
for i in range(0,4,2):
  a[0,i],a[2,i]=0,0
for i in range(1,4,2):
  a[1,i],a[3,i]=0,0

a

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [50]:
# 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format)and load it.
a=["a","b","c"]
b=["d","e","f"]
np.array(a)
np.array(b)
c=np.hstack((a,b))
c
# how to make it compressed???

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [18]:
# 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.Select
a=np.random.rand(40)
a

array([0.71717105, 0.39522633, 0.35811168, 0.89371891, 0.14124523,
       0.27244968, 0.20747215, 0.152138  , 0.58680566, 0.52437817,
       0.41494506, 0.58881546, 0.76110815, 0.63696772, 0.39489213,
       0.93663144, 0.03964675, 0.56939474, 0.59121268, 0.35099238,
       0.0523872 , 0.80504799, 0.3723347 , 0.94957825, 0.19448347,
       0.86213054, 0.99381415, 0.95429798, 0.04273574, 0.76422231,
       0.10929356, 0.17649911, 0.41516205, 0.72017879, 0.14884976,
       0.48556195, 0.54509305, 0.79813883, 0.73296008, 0.91931789])

In [49]:
# 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.
num=7
a= np.arange(10)
a
b=a<num
c=a>num
print(a[b])
print(a[c])

[0 1 2 3 4 5 6]
[8 9]
